/***************************************************************************
 *   Copyright (C) 2005 by                                                 *
 *   Alejandro Perez Mendez     alex@um.es                                 *
 *   Pedro J. Fernandez Ruiz    pedroj@um.es                               *
 *                                                                         *
 *   This software may be modified and distributed under the terms         *
 *   of the Apache license.  See the LICENSE file for details.             *
 ***************************************************************************/
#ifndef OPENIKEV2EAPMETHOD_H
#define OPENIKEV2EAPMETHOD_H

#include <libopenikev2/bytearray.h>

namespace openikev2 {

    /**
     Abstract class that represents any EapMethod (EapClient or EapServer) and contains the common parts to both
     @author Alejandro Perez Mendez, Pedro J. Fernandez Ruiz <alex@um.es, pedroj@um.es>
    */
    class EapMethod : public Printable{
            /****************************** ATTRIBUTES ******************************/
        protected:
            auto_ptr<ByteArray> shared_key;                     /**< Shared key generated by the EAP method (if available) */

            /****************************** METHODS ******************************/
        public:
            /**
             * Sets the shared key value
             * @param shared_key Shared key
             */
            virtual void setSharedKey( auto_ptr<ByteArray> shared_key );

            /**
             * Gets the shared key value
             * @return Reference to the shared_key
             */
            virtual ByteArray* getSharedKey() const;

            virtual string toStringTab( uint8_t tabs ) const = 0;

            virtual ~EapMethod();

    };

}

#endif
